### ISSUE TITLE
neuroevolution flappy bird .mutate() missing

### ISSUE THREAD

**Issue by franciscogmm** [shiffman/Neural-Network-p5#13]
hi! just wanted to know how you mutated the brain/neural net? what aspects of it did you mutate? the hyper parameters? the # of hidden layers? # of neurons per hidden layer? i just noticed that it calls a fcn .mutate() but i couldn't find any function related to that.

thanks!

**Comment by wagenaartje** [comment]
This code can be found in `nn.js`:

```javascript
NeuralNetwork.prototype.mutate = function() {
  this.wih = Matrix.map(this.wih, mutate);
  this.who = Matrix.map(this.who, mutate);
}
```

Which basically applies this:

```javascript
// This is how we adjust weights ever so slightly
function mutate(x) {
  if (random(1) < 0.1) {
    var offset = randomGaussian() * 0.5;
    // var offset = random(-0.1, 0.1);
    var newx = x + offset;
    return newx;
  } else {
    return x;
  }
}
```

If you want more advanced mutation method, you may want to check out my neuro-evolution library: [Neataptic](https://github.com/wagenaartje/neataptic).

**Comment by franciscogmm** [comment]
Thank you! Very helpful!
