### ISSUE TITLE
There seems to be a problem with the matrix library

### ISSUE THREAD

**Issue by Rusu83** [shiffman/Neural-Network-p5#29]
My code:
var nn;
function setup() {
nn=new NeuralNetwork(2,3,5);
}
function draw() {
}

     The error:
172: Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
"%cDid you just try to use p5.js's str() function? If so, you may want to move it into your sketch's setup() function.\n\nFor more details, see: github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup"
73: Uncaught ReferenceError: Matrix is not defined

**Comment by shiffman** [comment]
This repo is now deprecated check out https://github.com/CodingTrain/Toy-Neural-Network-JS/. I think I'll archive it?
